name: Preview Deployment
on: pull_request
concurrency:
  group: ${{ github.head_ref || github.ref }}
  cancel-in-progress: true
jobs:
  Spawn-Database-Branch:
    runs-on: ubuntu-latest
    name: Spawn Database Branch
    env:
      PR_NUMBER: ${{ github.event.number }}
    outputs:
      BRANCH_DATABASE: ${{ steps.branch-credentials.outputs.BRANCH_DATABASE }}
      BRANCH_HOST: ${{ steps.branch-credentials.outputs.BRANCH_HOST }}
      BRANCH_PASSWORD: ${{ steps.branch-credentials.outputs.BRANCH_PASSWORD }}
      BRANCH_USER: ${{ steps.branch-credentials.outputs.BRANCH_USER }}
    steps:
      - name: Get Latest Neonctl Release
        run: |
          curl -L \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}"\
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/unredundant/neonctl/releases/latest \
            -o neonctl_release.json
      - name: Get Assets URL
        uses: sergeysova/jq-action@v2
        id: get_assets_url
        with:
          cmd: jq .assets_url neonctl_release.json -r
      - name: Get Assets
        run: |
          curl -L \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}"\
            -H "X-GitHub-Api-Version: 2022-11-28" \
            ${{ steps.get_assets_url.outputs.value }} \
            -o assets.json
      - name: Get Asset ID
        uses: sergeysova/jq-action@v2
        id: get_asset_id
        with:
          cmd: jq '.[] | select(.name == "neonctl-linux.kexe") | .id' assets.json -r
      - name: Install Neonctl
        run: |
          wget \
            --header="X-GitHub-Api-Version: 2022-11-28" \
            --header='Accept:application/octet-stream' \
            https://api.github.com/repos/unredundant/neonctl/releases/assets/${{ steps.get_asset_id.outputs.value }}  \
            -O neonctl.kexe
      - name: Prep for Neonctl (Delete once bug fixed)
        run: |
          mkdir -p $HOME/.config/neonctl
          chmod +x neonctl.kexe
      - name: Initialize Neonctl
        run: ./neonctl.kexe init ${{ secrets.NEON_API_TOKEN }}
      - name: Delete existing branch if present
        run: ./neonctl.kexe branch -p ${{ secrets.NEON_PROJECT_ID }} delete -n pr-${{ env.PR_NUMBER }} || true
      - name: Sleep for a lil bit (neon breaks otherwise, eventually replace with retry)
        run: sleep 10s
      - name: Spawn Database Branch
        run: ./neonctl.kexe branch -p ${{ secrets.NEON_PROJECT_ID }} create -n pr-${{ env.PR_NUMBER }} | tee branch.json
      - name: Set Database Branch Outputs
        id: branch-credentials
        run: | 
          echo "BRANCH_DATABASE=$(jq -r '.connection_uris[0].connection_parameters.database' branch.json)" >> "$GITHUB_OUTPUT"
          echo "BRANCH_HOST=$(jq -r '.connection_uris[0].connection_parameters.host' branch.json)" >> "$GITHUB_OUTPUT"
          echo "BRANCH_PASSWORD=$(jq -r '.connection_uris[0].connection_parameters.password' branch.json)" >> "$GITHUB_OUTPUT"
          echo "BRANCH_USER=$(jq -r '.connection_uris[0].connection_parameters.role' branch.json)" >> "$GITHUB_OUTPUT"
  Run-Migrations:
    runs-on: ubuntu-latest
    name: Run Migrations
    needs: Spawn-Database-Branch
    env:
      DATABASE_HOST: ${{ needs.Spawn-Database-Branch.outputs.BRANCH_HOST }}
      DATABASE_NAME: ${{ needs.Spawn-Database-Branch.outputs.BRANCH_DATABASE }}
      DATABASE_USER: ${{ needs.Spawn-Database-Branch.outputs.BRANCH_USER }}
      DATABASE_PASSWORD: ${{ needs.Spawn-Database-Branch.outputs.BRANCH_PASSWORD }}
      DATABASE_SSL_MODE: require
    steps:
      - uses: actions/checkout@v3
      - name: Install Atlas
        run: curl -sSf https://atlasgo.sh | sh
      - name: Run Migrations
        run: |
          atlas migrate apply \
            --url "postgres://${{ env.DATABASE_USER }}:${{ env.DATABASE_PASSWORD }}@${{ env.DATABASE_HOST }}/${{ env.DATABASE_NAME }}?ssl_mode=${{ env.DATABASE_SSL_MODE }}&search_path=public" \
            --dir "file://migrations?format=flyway"
  Deploy-Portfolio-Preview:
    runs-on: ubuntu-latest
    name: Portfolio
    environment:
      name: portfolio-preview
      url: ${{ steps.deploy.outputs.url }}
    needs:
      - Run-Migrations
      - Spawn-Database-Branch
    env:
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PORTFOLIO_PROJECT_ID }}
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
      DATABASE_HOST: ${{ needs.Spawn-Database-Branch.outputs.BRANCH_HOST }}
      DATABASE_NAME: ${{ needs.Spawn-Database-Branch.outputs.BRANCH_DATABASE }}
      DATABASE_USER: ${{ needs.Spawn-Database-Branch.outputs.BRANCH_USER }}
      DATABASE_PASSWORD: ${{ needs.Spawn-Database-Branch.outputs.BRANCH_PASSWORD }}
      DATABASE_SSL_MODE: require
    steps:
      - uses: actions/checkout@v3
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}
      - name: Build Project Artifacts
        run: vercel build --token=${{ secrets.VERCEL_TOKEN }}
      - name: Deploy Project Artifacts to Vercel
        id: deploy
        run: echo "url=$(vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }})" >> "$GITHUB_OUTPUT"
  Deploy-Portfolio-Admin-Preview:
    runs-on: ubuntu-latest
    name: Admin
    environment:
      name: admin-preview
      url: ${{ steps.deploy.outputs.url }}
    needs:
      - Run-Migrations
      - Spawn-Database-Branch
    env:
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PORTFOLIO_ADMIN_PROJECT_ID }}
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
      DATABASE_HOST: ${{ needs.Spawn-Database-Branch.outputs.BRANCH_HOST }}
      DATABASE_NAME: ${{ needs.Spawn-Database-Branch.outputs.BRANCH_DATABASE }}
      DATABASE_USER: ${{ needs.Spawn-Database-Branch.outputs.BRANCH_USER }}
      DATABASE_PASSWORD: ${{ needs.Spawn-Database-Branch.outputs.BRANCH_PASSWORD }}
      DATABASE_SSL_MODE: require
    steps:
      - uses: actions/checkout@v3
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}
      - name: Build Project Artifacts
        run: vercel build --token=${{ secrets.VERCEL_TOKEN }}
      - name: Deploy Project Artifacts to Vercel
        id: deploy
        run: echo "url=$(vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }})" >> "$GITHUB_OUTPUT"